### ISSUE TITLE
modify libc/libc++ to handle the rop-defender-testcases

### ISSUE THREAD

**Issue by ievans** [riscv-mit/riscv-isa-sim#10]
Selectively enabling our tags only for the userspace program, ensure that we can successfully run all of the programs here:
https://github.com/riscv-mit/riscv-isa-sim/tree/tags/rop-defender-tests

Some will work on the proxy kernel but others will need full Linux; we might as well go full Linux anyways as we need to make the changes to full libc not just the stripped-down newlib. Also, we can use the CHERI FreeBSD as a reference. For instance this is how they handle setjmp: https://github.com/CTSRD-CHERI/cheribsd/commits/master/include/setjmp.h

**Comment by jugonz** [comment]
progress:
- exception/exception2 not working
- setjmp/setjmp2/setjmp4 seem to work (setjmp3 needs to be uncommented)
- signals2 and signals3 seem to work

**Comment by jugonz** [comment]
exception/exception2 work with modified libgcc_s.so.1 (provided in 8af2e6a54e7628d3e6bd358996246ff117005a3f)

**Comment by jugonz** [comment]
setjmp3 works now.
signals2/signals3 are now signals, and works.
signals2, 3, 4 are new signals test programs that all work.

**Comment by jugonz** [comment]
'Selectively enabling our tags only for the userspace program' is a good goal, but I think it belongs as a separate issue as we can successfully run all the test programs in single-file-tests/rop-defender-tests.
Closing this issue.
